### ISSUE TITLE
Cake 3.3 compatibility

### ISSUE THREAD

**Issue by Zuluru** [voycey/salesforce-datasource-cakephp-3.x#6]
Looks like some bits of this don't work with Cake 3.3. I've done a PR for some easy fixes, but have additional things I'm not sure how to fix. Happy to work towards resolving those, but don't have experience with ORM internals, so I have some questions to get me going in the right direction. What's the best way to ask them? Here? Email? Skype?

**Comment by voycey** [comment]
Thanks for these, I havent been using this plugin since I released this so
it hasn't been updated unfortunately!
Send over an email to voycey@gmail.com and ill get in touch next week to
take a look and discuss getting stuff merged in :)

On 13 Aug 2017 00:33, "Zuluru" <notifications@github.com> wrote:

Looks like some bits of this don't work with Cake 3.3. I've done a PR for
some easy fixes, but have additional things I'm not sure how to fix. Happy
to work towards resolving those, but don't have experience with ORM
internals, so I have some questions to get me going in the right direction.
What's the best way to ask them? Here? Email? Skype?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/voycey/cakephp-salesforce/issues/6>, or mute the thread

**Comment by voycey** [comment]
These changes look fine, Ill merge them in, happy to provide advice on any future changes you want to make, I don't have an active Salesforce subscription presently so I havent done much work on this but I'm sure I can provide some decent input :)
